ci: remove linting from husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,22 +5,11 @@ echo 'RUNNING GIT HOOKS'
 
 echo 'Checking Validity Of Types'
 
-yarn type-check || (
+pnpm type-check || (
     echo '⛔️ There is a TYPE ERROR on your code, please fix it and do commit again ⛔️';
     false;
 )
 
-echo 'No Type Error ✅'
+echo '🎉 No Type Error found: committing this now.... ✨🚀🏄‍♂️🍻'
 
-echo 'Running linter'
-
-# Check ESLint Standards
-yarn lint ||
-(
-    echo '⛔️ There is an ESLINT ERROR on your code, please fix it and do commit again ⛔️';
-    false;
-)
-
-echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
-
-npx lint-staged
+pnpm exec lint-staged
